#include <iostream.h>
#include <conio.h>

int Pilihan;
char kode;

int main () {
cout<< " Daftar Lokasi Pembuatan Produk Komputer :\n";
cout<<" A. Amerika \n J. Jepang \n K. Korea \n C. China \n G.German \n T. Taiwan\n";
 cout<<" Masukkan Pilihan Anda ( A,J,K,C,G,T) : "; cin >> Pilihan;
	switch(Pilihan) {
case 1 :
	   ="Anda Memilih Amerika";
   break;
case 2 :
	J="Anda Memilih Jepang";
   break;
case 3 :
	K="Anda Memilih Korea";
   break;
case 4 :
	C="Anda Memilih China";
   break;
case 5 :
	G="Anda Memilih German";
   break;
case 6 :
	T="Anda Memilih Taiwan";
   break; }
 cout << kode;}

